# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]

  # Directory with the serverless Lambda functions to deploy to AWS.
  
  command = "npm run lambda-build && bundle exec middleman build"
  functions = "lambda" #  netlify-lambda reads this
  publish = "build"

