backend:
  name: git-gateway

local_backend: true

media_folder: source/images/uploads
public_folder: /images/uploads
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: blog
    label: Blog
    folder: source/posts/
    extension: .html.markdown
    format: frontmatter
    create: true
    slug: '{{slug}}'
    fields:
      - {label: Published, name: published, widget: boolean, default: true}
      - {label: Title, name: title, widget: string}
      - {label: Category, name: category, widget: select, options: [{label: "Climate", value: climate}, {label: "Opinion", value: opinion},  {label: "Travel", value: travel}, {label: "One of the 100,000", value: one_of_the_100000}, {label: "Flight Free 2020", value: flight_free_2020}, {label: "Testimonials", value: testimonials}] }
      - {label: Publish Date, name: date, widget: datetime}
      - {label: Cover image, name: cover_image, widget: image}
      - {label: Summary, name: summary, widget: text}
      - {label: Author, name: author, widget: relation, collection: authors, valueField: name, searchFields: [name]}
      - {label: Read time, name: read_time_minute, widget: number}
      - {label: Body, name: body, widget: markdown}
  - name: podcasts
    label: Podcasts
    folder: data/podcasts
    format: yml
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: date}
      - {label: Cover image, name: cover_image, widget: image}
      - {label: Summary, name: summary, widget: text}
      - {label: URL, name: url, widget: string}
  - name: videos
    label: Videos
    folder: data/videos
    format: yml
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Publish Date, name: date, widget: date}
      - {label: Cover image, name: cover_image, widget: image}
      - {label: Summary, name: summary, widget: text}
      - {label: URL, name: url, widget: string}
  - name: faqs
    label: FAQs
    files:
      - label: General FAQs about flying
        name: general
        file: "data/faqs/general.yml"
        fields:
          - label: FAQs
            name: faqs
            widget: list
            allow_add: true
            fields:
            - {label: Question, name: question, widget: string}
            - {label: Answer, name: answer, widget: markdown}
      - label: Specific FAQs about the campaign
        name: specific
        file: "data/faqs/specific.yml"
        fields:
          - label: FAQs
            name: faqs
            widget: list
            allow_add: true
            fields:
            - {label: Question, name: question, widget: string}
            - {label: Answer, name: answer, widget: markdown}
  - name: authors
    label: Blog Authors
    folder: data/authors/
    format: yml
    create: true
    identifier_field: name
    fields:
      - {label: Name, name: name, widget: string}
      - {label: Avatar, name: avatar, widget: image}
  - name: team
    label: Team
    files:
      - label: Members
        name: members
        file: "data/team.yml"
        fields:
          - label: Members
            name: members
            widget: list
            allow_add: true
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Role, name: role, widget: string}
              - {label: Bio, name: bio, widget: text}
              - {label: Photo, name: photo, widget: image}
  - name: advisorygroup
    label: Advisory Group
    files:
      - label: Advisory Group Members
        name: advisorygroup
        file: "data/advisorygroup.yml"
        fields:
          - label: Members
            name: members
            widget: list
            allow_add: true
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Website, name: url, widget: string}
              - {label: Role, name: description, widget: string}
              - {label: Bio, name: bio, widget: text}
